### ISSUE TITLE
Job Search

### ISSUE THREAD

**Issue by Sylvieleclerc** [vrcareersite/betatestclient#100]
In French -
Villes - Start with Upper case
All = Toutes
MONTRÉAL (put accent on E)

Catégorie d'emploi
All = Toutes

![image](https://cloud.githubusercontent.com/assets/5117554/5900593/f59f15aa-a538-11e4-9e30-fc09c550bfaf.png)

**Comment by thenna** [comment]
Data is updated as from ATS, can we overwrite that?

**Comment by Sylvieleclerc** [comment]
On French side please leave city names as is but update:
Ville with Upper case for first letter
and replace All by: Toutes

Thx

**Comment by thenna** [comment]
Updated..

**Comment by Sylvieleclerc** [comment]
OK confirmed
