### ISSUE TITLE
Twitter - Message by default

### ISSUE THREAD

**Issue by Sylvieleclerc** [vrcareersite/betatestclient#101]
Update message by default:
English:
VIA Rail Canada is hiring: "English Job title" in "City" "ENG link to Job description" http://http//viarailpro.azurewebsites.net/fr/job-detail?%C3%A9lectricien-de-voiture-ferroviaire-toronto-ontario-canada-jobid-2120 - Can we shorten?

French:
VIA Rail Canada embauche: "French Job title" à "City"  "FR link to Job description"  - Can we shorten?

![image](https://cloud.githubusercontent.com/assets/5117554/5900818/fc1ca030-a53a-11e4-9c13-6bf649d29704.png)

**Comment by thenna** [comment]
Updated..

**Comment by Sylvieleclerc** [comment]
Ok text updated
