### ISSUE TITLE
Warning notice - Home Page

### ISSUE THREAD

**Issue by Sylvieleclerc** [vrcareersite/betatestclient#102]
Please activate warning notive below Highlights section on Home Page with the following text:

Warning
In order to upload your Resume, please use another browser than Internet Explorer 11.  For example, you can use Firefox, Chrome. Thank you.

Avertissement
Veuillez utiliser un autre fureteur qu’Internet Explorer 11 si vous souhaitez télécharger votre Curriculum Vitae.  Vous pouvez utiliser par exemple Firefox, Chrome.  Merci.

**Comment by thenna** [comment]
Do you want it updated below as a separate box or withing in the Highlights section..

Please confirm..

**Comment by Sylvieleclerc** [comment]
In the separate section below (which has been hidden).

Thank you

De : thenna [mailto:notifications@github.com]
Envoyé : 26 janvier 2015 13:31
À : vrcareersite/betatestclient
Cc : Sylvie Leclerc
Objet : Re: [betatestclient] Warning notice - Home Page (#102)

Do you want it updated below as a separate box or withing in the Highlights section..

Please confirm..

**Comment by thenna** [comment]
Updated

**Comment by Sylvieleclerc** [comment]
Ok confirmed

**Comment by Sylvieleclerc** [comment]
Could pls put all text in red pls?

**Comment by thenna** [comment]
Updated..

**Comment by Sylvieleclerc** [comment]
Ok closed
