### ISSUE TITLE
Update Profile - IFrame Links to adjust

### ISSUE THREAD

**Issue by Sylvieleclerc** [vrcareersite/betatestclient#103]
Please update the IFrame links as they do not display the right Iframes... Thank you

English:

https://cvm-viarail.cvmanager.com/cvm5/displaypage.aspx?region=qc&tp1=cvformupd&lang=e

French:

https://cvm-viarail.cvmanager.com/cvm5/displaypage.aspx?region=qc&tp1=cvformupd&lang=f

**Comment by thenna** [comment]
Updated..

**Comment by Sylvieleclerc** [comment]
Ok confirmed
