### ISSUE TITLE
https://career.viarail.ca/fr/why-choose-us/location - Header Job listing

### ISSUE THREAD

**Issue by Sylvieleclerc** [vrcareersite/betatestclient#109]
pls use the same as the job listing

FRENCH
![image](https://cloud.githubusercontent.com/assets/5117554/5918109/f4ce374a-a5f2-11e4-8227-c856b70bd289.png)

ENGLISH
![image](https://cloud.githubusercontent.com/assets/5117554/5918122/0a07499e-a5f3-11e4-81cd-b6ed21242727.png)

**Comment by thenna** [comment]
Updated..

**Comment by Sylvieleclerc** [comment]
Ok confirmed
