### ISSUE TITLE
Urgent - job description

### ISSUE THREAD

**Issue by Sylvieleclerc** [vrcareersite/betatestclient#111]
Design is in default. See below. + Right column is below job description not on the right... under Chrome and IE

![image](https://cloud.githubusercontent.com/assets/5117554/5919692/3fa1799c-a604-11e4-9f09-957e198c0165.png)

Are you sure you updated the CVM Apply I Frame starting with cvm- ?

**Comment by thenna** [comment]
Updated.

**Comment by Sylvieleclerc** [comment]
Ok confirmed
