### ISSUE TITLE
Spontaneous aplication

### ISSUE THREAD

**Issue by Sylvieleclerc** [vrcareersite/betatestclient#112]
Put link also on the main title

Can we have the text below underlined so that we understand it is a clickable link.
![image](https://cloud.githubusercontent.com/assets/5117554/5920051/8abe058c-a607-11e4-85dc-25bb2f0543e4.png)

**Comment by thenna** [comment]
Updated.

**Comment by Sylvieleclerc** [comment]
Ok confirmed
