### ISSUE TITLE
Job description fields both Site + Facebook

### ISSUE THREAD

**Issue by Sylvieleclerc** [vrcareersite/betatestclient#114]
Pls update as per the specs defined in the Excel - Fields are missing
Here is the listing which was defined in ENG and French:

Job Title | Titre du poste 
Reference Number  |  Numéro de référence : to be adjusted as it does not display the right ref. (see below for screen caputre as seen below)
Branch | Direction
Status | Statut
Location | Lieu : City | Ville + Province | Province  
Annual Salary | Salaire annuel
# of positions to be filled | Nombre de postes disponibles

Application deadline | Date limite

![image](https://cloud.githubusercontent.com/assets/5117554/5926259/ae38c24c-a637-11e4-85d2-9eeb9999898f.png)

**Comment by thenna** [comment]
Updated..

**Comment by Sylvieleclerc** [comment]
Ok confirmed
