### ISSUE TITLE
Facebook - French + English - Similar Job text

### ISSUE THREAD

**Issue by Sylvieleclerc** [vrcareersite/betatestclient#115]
Pls update message as follow:
Désolés, nous n’avons pu trouver aucune autre offre d’emploi similaire.

Sorry, no other similar job could be found.

![image](https://cloud.githubusercontent.com/assets/5117554/5926634/77fc345e-a63a-11e4-8a51-7c93d3faacae.png)

**Comment by thenna** [comment]
Updated..

**Comment by Sylvieleclerc** [comment]
Ok closed
