### ISSUE TITLE
Mobile - Header Job listing

### ISSUE THREAD

**Issue by Sylvieleclerc** [vrcareersite/betatestclient#118]
Pls update in French Header

Job title = Titre du poste
Blamk = Emplacement

![image](https://cloud.githubusercontent.com/assets/5117554/5939339/d5313732-a6d0-11e4-958f-f4eb84703515.png)

**Comment by thenna** [comment]
Updated..

**Comment by Sylvieleclerc** [comment]
Ok confirmed
