### ISSUE TITLE
Job removal

### ISSUE THREAD

**Issue by Sylvieleclerc** [vrcareersite/betatestclient#121]
Are you able to confirm at what time was removed the job listed first int he capture below:
The ABC job test

Is it possible it was removed first from the full job listing and then from the listing provided in Customer Service Career Track?

![image](https://cloud.githubusercontent.com/assets/5117554/5950986/ed409008-a72e-11e4-829a-f11c4b50cf23.png)

**Comment by thenna** [comment]
Removed ..

**Comment by Sylvieleclerc** [comment]
Can you pls confirm if job scraping refresh is happening at the same time on all job listings of the Career site?

**Comment by thenna** [comment]
Yes.. it is.. and below is the scraping schedule.

12AM, 04AM, 08AM, 12PM, 04PM, 08PM in EST

**Comment by Sylvieleclerc** [comment]
OK confirmed
