### ISSUE TITLE
Map location

### ISSUE THREAD

**Issue by Sylvieleclerc** [vrcareersite/betatestclient#16]
Can we better adjust the map on Canada?
Get:
![image](https://cloud.githubusercontent.com/assets/5117554/5438562/393ae4e6-8447-11e4-81f4-1c0c6888fe8c.png)

INSTEAD OF:
![image](https://cloud.githubusercontent.com/assets/5117554/5438534/0996fe28-8447-11e4-93d8-c30fe23dd907.png)

**Comment by thenna** [comment]
Updated
