### ISSUE TITLE
incorrect career section title

### ISSUE THREAD

**Issue by ph302014** [vrcareersite/betatestclient#18]
the customer service section on the English site has the wrong title. the title should be "customer service" ![career section title](https://cloud.githubusercontent.com/assets/10053560/5667300/b11a64aa-9734-11e4-9ef3-cbc4a124dcc3.png)

**Comment by thenna** [comment]
Updated.. 

Note : This was updated initially as per the PSD provided earlier. And still we are waiting for content for each section of the site.
