### ISSUE TITLE
http://viarail.azurewebsites.net/en/career-areas

### ISSUE THREAD

**Issue by Sylvieleclerc** [vrcareersite/betatestclient#21]
Remove duplicate words and put the same hyperlink as Read More button.

![image](https://cloud.githubusercontent.com/assets/5117554/5724613/cdd08ab8-9b1a-11e4-8129-12fd2de0e54f.png)

**Comment by thenna** [comment]
Updated.

**Comment by Sylvieleclerc** [comment]
Hyperlinks are not redirecting to the relevant specific Career Track

![image](https://cloud.githubusercontent.com/assets/5117554/5823154/6c7fccae-a0a8-11e4-80b3-4ea8667456e1.png)

**Comment by Sylvieleclerc** [comment]
Confirmed
