### ISSUE TITLE
http://viarail.azurewebsites.net/en/career-areas#

### ISSUE THREAD

**Issue by Sylvieleclerc** [vrcareersite/betatestclient#22]
Put same hyperlink as Read more button

![image](https://cloud.githubusercontent.com/assets/5117554/5724666/1b49c98a-9b1b-11e4-8865-e72c4cb11cba.png)

**Comment by thenna** [comment]
Updated.

**Comment by Sylvieleclerc** [comment]
Not working on my side, still redirecting to the top of the Main Career Track Page

**Comment by Sylvieleclerc** [comment]
OK confirmed
