### ISSUE TITLE
http://viarail.azurewebsites.net/en/career-areas/customer-service#  - remove link on job title

### ISSUE THREAD

**Issue by Sylvieleclerc** [vrcareersite/betatestclient#24]
Font color does not look like the same as the rest...

![image](https://cloud.githubusercontent.com/assets/5117554/5724760/d157828a-9b1b-11e4-80a8-cdd57670bfd0.png)

Come aboard and apply! Hyperlink should redirect to Spontaneous applications.

**Comment by Sylvieleclerc** [comment]
Job titles in this section are not clickable. Bold font pls

**Comment by thenna** [comment]
Updated.

**Comment by Sylvieleclerc** [comment]
Job Title seems to be still clickable, pls remove links. Just put title in bold font.

Font color still look more black than the rest

Hyperlink for apply is still redirecting to the same page... Pls just remove Hyperlink

**Comment by Sylvieleclerc** [comment]
OK for hyperlink
OK for font color

Remove hyperlinks on job titles - Put bold font only
![image](https://cloud.githubusercontent.com/assets/5117554/5831462/29b5b2fe-a101-11e4-8481-281f564bd3f4.png)

**Comment by thenna** [comment]
Updated..

**Comment by Sylvieleclerc** [comment]
Confirmed
