### ISSUE TITLE
http://viarail.azurewebsites.net/en/career-areas/train-maintenance-and-operations# remove link on job title

### ISSUE THREAD

**Issue by Sylvieleclerc** [vrcareersite/betatestclient#25]
Hyperlink you redirect to Google Map locations Page
![image](https://cloud.githubusercontent.com/assets/5117554/5724815/4147e292-9b1c-11e4-9c4a-f4d070a54971.png)

Job Titles not clickable. Bold Font.

Come aboard and apply now! Apply now redirect to spontaneous application Page.

**Comment by Sylvieleclerc** [comment]
Should have the same click and open/hide for each job title section (use job title as main title) and show beginning of the paragraph as in Customer service Page:
![image](https://cloud.githubusercontent.com/assets/5117554/5724877/9b005954-9b1c-11e4-9d0b-e93bb797b708.png)

**Comment by thenna** [comment]
Updated.

**Comment by Sylvieleclerc** [comment]
Job Titles should not be clickable. Please remove.
Bold Font.

**Comment by thenna** [comment]
Updated..

**Comment by Sylvieleclerc** [comment]
Confirmed
