### ISSUE TITLE
http://viarail.azurewebsites.net/en/why-choose-us/diversity-and-inclusion

### ISSUE THREAD

**Issue by Sylvieleclerc** [vrcareersite/betatestclient#29]
Both in French and English
![image](https://cloud.githubusercontent.com/assets/5117554/5733130/3ec404c4-9b6c-11e4-9555-9e13173d416b.png)

**Comment by thenna** [comment]
Updated.

**Comment by Sylvieleclerc** [comment]
OK confirmed
