### ISSUE TITLE
Social Job Matcher - sign out - Update FRENCH

### ISSUE THREAD

**Issue by Sylvieleclerc** [vrcareersite/betatestclient#31]
Would make it more obvious by adding "sign out" close to the cross

![image](https://cloud.githubusercontent.com/assets/5117554/5733219/b3d7ae54-9b6d-11e4-86a2-7255e5047096.png)

**Comment by thenna** [comment]
Updated.

**Comment by Sylvieleclerc** [comment]
Ok for English.

In French: Fermer

**Comment by thenna** [comment]
Updated

**Comment by Sylvieleclerc** [comment]
Confirmed
