### ISSUE TITLE
http://viarail.azurewebsites.net/en/job-toolbox/our-hiring-process

### ISSUE THREAD

**Issue by Sylvieleclerc** [vrcareersite/betatestclient#33]
Create a link on "why you should come on board" in the very first sentence to redirect to the relevant Page: Main - Why come on board

Create a link on "three main career tracks" (second sentence) to http://viarail.azurewebsites.net/en/career-areas

Second bullet point: "spontaneous application" create link to relevant page

**Comment by thenna** [comment]
Updated.

**Comment by Sylvieleclerc** [comment]
Ok confirmed
