### ISSUE TITLE
http://viarail.azurewebsites.net/en/job-toolbox - title

### ISSUE THREAD

**Issue by Sylvieleclerc** [vrcareersite/betatestclient#35]
![image](https://cloud.githubusercontent.com/assets/5117554/5733631/f47e6bfe-9b73-11e4-959e-e409ae08097e.png)

replace Picture of Banner and Headline by same as Home Page. Both French and English

**Comment by thenna** [comment]
Updated.

**Comment by Sylvieleclerc** [comment]
Add space after Keeping track title and before 1st paragraph

![image](https://cloud.githubusercontent.com/assets/5117554/5831773/3f761326-a107-11e4-97ba-52b90e7410d0.png)

**Comment by Sylvieleclerc** [comment]
Ok confirmed
