### ISSUE TITLE
http://viarailpro.azurewebsites.net/en/career-areas/train-maintenance-and-operations

### ISSUE THREAD

**Issue by Sylvieleclerc** [vrcareersite/betatestclient#38]
Remove words

![image](https://cloud.githubusercontent.com/assets/5117554/5806451/4f58587e-9fe7-11e4-93b7-b0de9f9f1412.png)

**Comment by thenna** [comment]
Updated.

**Comment by Sylvieleclerc** [comment]
Confirmed
