### ISSUE TITLE
http://viarailpro.azurewebsites.net/fr/career-areas/train-maintenance-and-operations

### ISSUE THREAD

**Issue by Sylvieleclerc** [vrcareersite/betatestclient#39]
Adjust as follows

![image](https://cloud.githubusercontent.com/assets/5117554/5806860/543bcfc0-9feb-11e4-9a49-07ee5839bdfe.png)

**Comment by Sylvieleclerc** [comment]
![image](https://cloud.githubusercontent.com/assets/5117554/5806897/96153bd4-9feb-11e4-9be3-329b071740a5.png)

**Comment by thenna** [comment]
Updated.

**Comment by Sylvieleclerc** [comment]
Confirmed
