### ISSUE TITLE
job tool box

### ISSUE THREAD

**Issue by ph302014** [vrcareersite/betatestclient#4]
there should be a list of featured jobs here:
![image](https://cloud.githubusercontent.com/assets/10053560/5272762/d85f8d78-7a4d-11e4-96fe-c5b4c0d0652c.png)

**Comment by thenna** [comment]
Updated, we are not showing up top 5 jobs..

It would be best if we show different jobs based on pages. Please let me know.

**Comment by ph302014** [comment]
yes I believe the career sections shuold show jobs pertinent to the section...
as for the other pages, the top 5 jobs should be listed according to the latest posting date.
is this possible?

**Comment by thenna** [comment]
Resolved..
