### ISSUE TITLE
http://viarailpro.azurewebsites.net/fr/why-choose-us/veterans-program

### ISSUE THREAD

**Issue by Sylvieleclerc** [vrcareersite/betatestclient#43]
Remove struck text and replace by
First line: tous les services
Second line: de Compagnie

![image](https://cloud.githubusercontent.com/assets/5117554/5807371/bfdc8d8c-9ff0-11e4-84e4-708e6c9bd6e8.png)

**Comment by Sylvieleclerc** [comment]
Remove highlighted sentence and replace by "to all departments."

![image](https://cloud.githubusercontent.com/assets/5117554/5807899/977e9a92-9ff5-11e4-901f-ca9ae9c8630e.png)

**Comment by thenna** [comment]
Updated.

**Comment by Sylvieleclerc** [comment]
Confirmed
