### ISSUE TITLE
http://viarailpro.azurewebsites.net/fr/why-choose-us/diversity-and-inclusion

### ISSUE THREAD

**Issue by Sylvieleclerc** [vrcareersite/betatestclient#44]
Please update second bullet point as follow:

• Planifier et mettre en œuvre des programmes, des systèmes, des politiques et des pratiques qui visent à diminuer toutes formes de discrimination, qui font la promotion de possibilités d’emploi égales et qui favorisent la mise en place d’une main-d’œuvre représentative.

**Comment by thenna** [comment]
Updated.

**Comment by Sylvieleclerc** [comment]
Confirmed
