### ISSUE TITLE
http://viarailpro.azurewebsites.net/fr/why-choose-us/benefits

### ISSUE THREAD

**Issue by Sylvieleclerc** [vrcareersite/betatestclient#45]
Bigger font size for bullet listing - Both French and English

![image](https://cloud.githubusercontent.com/assets/5117554/5807550/6b834a58-9ff2-11e4-934d-5b247b5b4a7b.png)

**Comment by thenna** [comment]
Updated

**Comment by Sylvieleclerc** [comment]
Confirmed
