### ISSUE TITLE
http://viarailpro.azurewebsites.net/fr/why-choose-us/career-development

### ISSUE THREAD

**Issue by Sylvieleclerc** [vrcareersite/betatestclient#46]
Remove outlined sentence (first sentence). Both French and English

![image](https://cloud.githubusercontent.com/assets/5117554/5807680/9b036d0c-9ff3-11e4-9a12-37b93db802aa.png)

**Comment by thenna** [comment]
Updated

**Comment by Sylvieleclerc** [comment]
Confirmed
