### ISSUE TITLE
http://viarailpro.azurewebsites.net/en/why-choose-us  semi-column

### ISSUE THREAD

**Issue by Sylvieleclerc** [vrcareersite/betatestclient#48]
Add bullet point

Remove "s" at the end of "open"

![image](https://cloud.githubusercontent.com/assets/5117554/5807831/1c3a3bca-9ff5-11e4-8bac-8f32cb0ed292.png)

**Comment by thenna** [comment]
Updated

**Comment by Sylvieleclerc** [comment]
OK

First bullet pls replace period by semi-column

**Comment by thenna** [comment]
Updated..

**Comment by Sylvieleclerc** [comment]
Confirmed
