### ISSUE TITLE
Home Page - Highlights

### ISSUE THREAD

**Issue by Sylvieleclerc** [vrcareersite/betatestclient#49]
Both in French and English

Link for Read more:
French : http://viarailpro.azurewebsites.net/fr/career-areas
ENG : http://viarailpro.azurewebsites.net/en/career-areas

![image](https://cloud.githubusercontent.com/assets/5117554/5808232/42fbc78e-9ff9-11e4-8559-5cdea23d7107.png)

**Comment by thenna** [comment]
Updated

**Comment by Sylvieleclerc** [comment]
Confirmed
