### ISSUE TITLE
update my profile

### ISSUE THREAD

**Issue by ph302014** [vrcareersite/betatestclient#5]
there is no save feature when updating my profile:
![image](https://cloud.githubusercontent.com/assets/10053560/5272926/b8000510-7a4f-11e4-8943-4e2e212a24ba.png)

**Comment by thenna** [comment]
Updated in stg. Now save button will show upon with scroll. Need to add code for auto height.

Please add the below code in your end.. once updated let me know based on that, we can update in our end to set the auto height.

<script type="text/javascript">
$(document).ready(function(){
window.parent.postMessage($("body").height(), "*");
});
</script>

**Comment by ph302014** [comment]
I can now save my updates, what do you mean exactly by code for auto height?
