### ISSUE TITLE
http://viarailpro.azurewebsites.net/fr/job-toolbox - Main pic and headline

### ISSUE THREAD

**Issue by Sylvieleclerc** [vrcareersite/betatestclient#53]
Pls update as per Home Page - Both in French & English

![image](https://cloud.githubusercontent.com/assets/5117554/5809996/46fa7394-a00d-11e4-9ffa-1b0251e0b783.png)

**Comment by thenna** [comment]
Updated..

**Comment by Sylvieleclerc** [comment]
Confirmed
