### ISSUE TITLE
http://viarailpro.azurewebsites.net/fr/why-choose-us - headline

### ISSUE THREAD

**Issue by Sylvieleclerc** [vrcareersite/betatestclient#54]
Pls update headline in French and English

![image](https://cloud.githubusercontent.com/assets/5117554/5810031/c7cc38cc-a00d-11e4-8b23-1c80373a1d1b.png)

![image](https://cloud.githubusercontent.com/assets/5117554/5810025/beb435aa-a00d-11e4-8733-4b1ec94b4285.png)

**Comment by thenna** [comment]
Updated..

**Comment by Sylvieleclerc** [comment]
Confirmed
