### ISSUE TITLE
Update Pic for Benefits + Values + Career Dev. + Diversity

### ISSUE THREAD

**Issue by Sylvieleclerc** [vrcareersite/betatestclient#57]
Benefits: 
Values: 
Career Development: 
Diversity and inclusion: 

with the following one
![2015-01-20 14-50-30](https://cloud.githubusercontent.com/assets/5117554/5825203/912ea34a-a0b7-11e4-8043-e86c79197123.png)

**Comment by thenna** [comment]
Updated..

**Comment by Sylvieleclerc** [comment]
Confirmed
