### ISSUE TITLE
http://viarailpro.azurewebsites.net/fr/career-areas/train-maintenance-and-operations - accordion

### ISSUE THREAD

**Issue by Sylvieleclerc** [vrcareersite/betatestclient#60]
Should have the same click and open/hide for (both FRENCH and ENGLISH)

![image](https://cloud.githubusercontent.com/assets/5117554/5831495/fb795412-a101-11e4-9352-8e4d79615fa3.png)

**Comment by thenna** [comment]
> > Fixed – clarification - below first accordian three paragraphs need to be as accordion?

**Comment by Sylvieleclerc** [comment]
Good as it is but I would put accordions closed by default

**Comment by Sylvieleclerc** [comment]
OK confirmed
