### ISSUE TITLE
Facebook share

### ISSUE THREAD

**Issue by Sylvieleclerc** [vrcareersite/betatestclient#69]
job title to be updated + link

![image](https://cloud.githubusercontent.com/assets/5117554/5837237/5cccb1e8-a14b-11e4-82b2-cbe4a6ff2d0c.png)

**Comment by thenna** [comment]
Updated.

**Comment by Sylvieleclerc** [comment]
Good for LinkedIn but still same issue for facebook

![image](https://cloud.githubusercontent.com/assets/5117554/5865506/d2dcf598-a257-11e4-9910-dfe7b312f4cc.png)

**Comment by thenna** [comment]
I am working on it.. give me sometime to get it fixed..

**Comment by thenna** [comment]
Updated..

**Comment by Sylvieleclerc** [comment]
Can you fix the display of logo when Fb pick this image?
Also, sometimes it picks up the logo, sometimes the main image, what is the defined rule?

![image](https://cloud.githubusercontent.com/assets/5117554/5979139/09e1cc6e-a873-11e4-80d0-3d5443b13f73.png)

**Comment by thenna** [comment]
This will take quite sometime for FB for the Cached job to show up the proper logo..

If you try to load the job link in the FB debugger, it will show up the proper image..

**Comment by Sylvieleclerc** [comment]
Ok confirmed
