### ISSUE TITLE
http://viarailpro.azurewebsites.net/fr/job-toolbox/our-hiring-process

### ISSUE THREAD

**Issue by Sylvieleclerc** [vrcareersite/betatestclient#72]
Add a "s" at the end of test

![image](https://cloud.githubusercontent.com/assets/5117554/5838847/19595c56-a158-11e4-8927-cc4349778c26.png)

**Comment by Sylvieleclerc** [comment]
Sorry I saw the update but need to add a "s" at the end of "préalable"

**Comment by thenna** [comment]
Updated..

**Comment by Sylvieleclerc** [comment]
Ok for word "Tests" but please also add a "s" at the end of "préalable"

**Comment by Sylvieleclerc** [comment]
OK confirmed
