### ISSUE TITLE
Locations Page - Messages when no jobs live

### ISSUE THREAD

**Issue by Sylvieleclerc** [vrcareersite/betatestclient#73]
Can we display more obviously the message when no jobs live... and update message

French:
Désolés, aucune offre d'emploi disponible pour le moment à cet emplacement. Assurez-vous de vous abonner à notre alerte-emploi.

English:
Sorry, no opportunities available at this time for this location. Make sure to register to our Job Alert.

Can we show at least the header of the chart and display message below? More like in English

![image](https://cloud.githubusercontent.com/assets/5117554/5841536/a275fe96-a16b-11e4-970b-9af628101d98.png)

![image](https://cloud.githubusercontent.com/assets/5117554/5841648/87b6498e-a16c-11e4-8d2c-88a5e0246394.png)

**Comment by thenna** [comment]
Updated..

**Comment by Sylvieleclerc** [comment]
I don't see any message lodaing when clicking on more info below (no jobs or job listing when jobs are active at this location)

**Comment by thenna** [comment]
Updated.. Now when we click on more info it will auto scroll to the content section.

if we have jobs it will show up , if not, no jobs message will get displayed..!

**Comment by Sylvieleclerc** [comment]
OK confirmed
