### ISSUE TITLE
Locations - Pin

### ISSUE THREAD

**Issue by Sylvieleclerc** [vrcareersite/betatestclient#74]
Please adjust Pin:
Name of: VIA Rail Canada
City Name: Lower case
More info below - Update in French: + d'info ci-bas

![image](https://cloud.githubusercontent.com/assets/5117554/5845962/39fc151c-a18e-11e4-922a-a71c6bb74886.png)

**Comment by thenna** [comment]
Updated..

**Comment by Sylvieleclerc** [comment]
Please adjust Pin - OK for Name of: VIA Rail Canada + City Name: Lower case

BUT "More info below" button needs to be updated in French: 
- d'info ci-bas

**Comment by Sylvieleclerc** [comment]
Ok Looks good.
Can you just confirm if cities name you are loading come directly from CVM (in French somme accents are missing Montréal or Upper case for some names such as St-Hyacinthe?

**Comment by Sylvieleclerc** [comment]
Very blurry image
Sorry text in French was modified I did not want a bullet but a plus sign in front of d'info

![image](https://cloud.githubusercontent.com/assets/5117554/5877964/4d8a2f4c-a2f1-11e4-9da7-b6a8ec5ff627.png)

**Comment by Sylvieleclerc** [comment]
Did not mean to close issue

**Comment by Sylvieleclerc** [comment]
![image](https://cloud.githubusercontent.com/assets/5117554/5894957/be037bb8-a4de-11e4-8812-61eb75c77873.png)

**Comment by Sylvieleclerc** [comment]
Still not make appear message for no job or job listing... Screen goes down but screen blank

![image](https://cloud.githubusercontent.com/assets/5117554/5894964/e0ea7258-a4de-11e4-9aad-b618669365be.png)

**Comment by Sylvieleclerc** [comment]
Button in French still need adjustment by adding a plus sign in front of text

![image](https://cloud.githubusercontent.com/assets/5117554/5918151/67ec3b8c-a5f3-11e4-9743-eb52e81cae23.png)

City name must start with upper case

**Comment by thenna** [comment]
Updated

**Comment by Sylvieleclerc** [comment]
Ok confirmed
