### ISSUE TITLE
Career Tracks

### ISSUE THREAD

**Issue by Sylvieleclerc** [vrcareersite/betatestclient#76]
Can we put hyperlinks on images and/or tiltles of each 3 section to redirect to the specific career track?

![image](https://cloud.githubusercontent.com/assets/5117554/5846170/aec5beec-a18f-11e4-84b5-59b7f76cf2dd.png)

**Comment by thenna** [comment]
Updated.

**Comment by Sylvieleclerc** [comment]
Ok confirmed
