### ISSUE TITLE
Facebook apply IFrame CVManager

### ISSUE THREAD

**Issue by Sylvieleclerc** [vrcareersite/betatestclient#83]
Why do we need to enter email address before applying? Is it stored?

Shouldn't we see the Iframe with Navigation of the Career Site?

![image](https://cloud.githubusercontent.com/assets/5117554/5861133/7d7241a8-a234-11e4-80f7-dc231f03d0e5.png)

**Comment by thenna** [comment]
This is the apply page..

Now we are implementing the Iframe based on the mail sent over..

**Comment by Sylvieleclerc** [comment]
OK
