### ISSUE TITLE
http://viarailpro.azurewebsites.net/en/career-areas/customer-service

### ISSUE THREAD

**Issue by Sylvieleclerc** [vrcareersite/betatestclient#89]
Text looks like cut on the right in the Job Alert

![image](https://cloud.githubusercontent.com/assets/5117554/5864214/28d59fcc-a24e-11e4-9421-b4b376ffd35e.png)

**Comment by thenna** [comment]
Updated..

**Comment by Sylvieleclerc** [comment]
OK confirmed
