### ISSUE TITLE
Facebook - confirm message send offer

### ISSUE THREAD

**Issue by Sylvieleclerc** [vrcareersite/betatestclient#94]
Please update translation for:
Merci de votre intérêt. Un lien vers cette offre d'emploi chez VIA Rail Canada été envoyé à sleclerc@illicohodes.com. Vous pourrez ainsi postuler à partir ce lien. Si vous ne le recevez pas, veuillez vérifier vos courriels indésirables. 

Please update in English at the end:
Thank you for your interest. A link to this job at VIA Rail Canada has been sent to sleclerc@illicohodes.com, so that you can apply. If you don’t receive it, please check your spam folder.

![image](https://cloud.githubusercontent.com/assets/5117554/5877703/74b52056-a2ef-11e4-88a1-a7d96872c199.png)

**Comment by thenna** [comment]
Updated..

**Comment by Sylvieleclerc** [comment]
Got an error message

![image](https://cloud.githubusercontent.com/assets/5117554/5926562/fb05b3d0-a639-11e4-9736-18ce0edd822c.png)

![image](https://cloud.githubusercontent.com/assets/5117554/5926566/00a82962-a63a-11e4-9412-88bd308aecf7.png)

**Comment by thenna** [comment]
This is working fine.. not able to replicate the issue..

**Comment by Sylvieleclerc** [comment]
Ok confirmed
