### ISSUE TITLE
Facebook - redirect when applying bad language

### ISSUE THREAD

**Issue by Sylvieleclerc** [vrcareersite/betatestclient#95]
When I tried to apply for a job in French, I was directed to the CVManager Apply Form in English...

![image](https://cloud.githubusercontent.com/assets/5117554/5877791/1ba4c2e0-a2f0-11e4-90d1-f17e7908638a.png)

![image](https://cloud.githubusercontent.com/assets/5117554/5877802/30727956-a2f0-11e4-9346-1f385e6c17ee.png)

**Comment by thenna** [comment]
Updated

**Comment by Sylvieleclerc** [comment]
OK right language but issue for Apply form (similar to what we have on Career SIte)

**Comment by thenna** [comment]
Updated..

**Comment by Sylvieleclerc** [comment]
Ok confirmed
