### ISSUE TITLE
Job description - Website

### ISSUE THREAD

**Issue by Sylvieleclerc** [vrcareersite/betatestclient#97]
Job description does not seem complete? We don't see the same big titles: 
Description - Exigences in French
Description - Requirements in English

On Career Site
![image](https://cloud.githubusercontent.com/assets/5117554/5878330/0a4af39e-a2f4-11e4-9ad4-67fae05af9b6.png)

CVM
![image](https://cloud.githubusercontent.com/assets/5117554/5878322/f7ca0eda-a2f3-11e4-86f3-fdeacc8ef62e.png)

**Comment by thenna** [comment]
Updated..

**Comment by Sylvieleclerc** [comment]
Please replace in French
Détails de l'emploi: by Description :

In English
Remove space before column for Description and Requirements

**Comment by thenna** [comment]
Updated..

**Comment by Sylvieleclerc** [comment]
Space still there - Pls update

![image](https://cloud.githubusercontent.com/assets/5117554/5951222/2a08bb8e-a732-11e4-8afd-593e7730b893.png)

**Comment by thenna** [comment]
Updated..

**Comment by Sylvieleclerc** [comment]
Ok confirmed
