### ISSUE TITLE
Spontaneous application - box title + text

### ISSUE THREAD

**Issue by Sylvieleclerc** [vrcareersite/betatestclient#98]
Please update
French: 
Main title: Candidature spontanée
Text: Ne manquez pas le train ! Soumettez votre candidature spontanée maintenant pour de futures possibilités d'emplois en lien avec votre champ d'intérêt.

English
Main title: Spontaneous application

**Comment by thenna** [comment]
Updated..

**Comment by Sylvieleclerc** [comment]
Ok confirmed
